#include "JavaScriptKey.h"

#include "JavaScriptNumeric.h"
#include "JavaScriptEnum.h"

namespace Atmos::Scripting::JavaScript
{
    v8::Local<v8::Value> Type<Input::Key>::Register(const RegistrationData& data)
    {
        const auto isolate = data.isolate;

        return CreateEnum<Input::Key>(
            *isolate,
            {
                { "LeftMouseButton", Input::Key::LeftMouseButton },
				{ "MiddleMouseButton", Input::Key::MiddleMouseButton },
				{ "RightMouseButton", Input::Key::RightMouseButton },
				{ "X1MouseButton", Input::Key::X1MouseButton },
				{ "X2MouseButton", Input::Key::X2MouseButton },

				{ "A", Input::Key::A },
				{ "B", Input::Key::B },
				{ "C", Input::Key::C },
				{ "D", Input::Key::D },
				{ "E", Input::Key::E },
				{ "F", Input::Key::F },
				{ "G", Input::Key::G },
				{ "H", Input::Key::H },
				{ "I", Input::Key::I },
				{ "J", Input::Key::J },
				{ "K", Input::Key::K },
				{ "L", Input::Key::L },
				{ "M", Input::Key::M },
				{ "N", Input::Key::N },
				{ "O", Input::Key::O },
				{ "P", Input::Key::P },
				{ "Q", Input::Key::Q },
				{ "R", Input::Key::R },
				{ "S", Input::Key::S },
				{ "T", Input::Key::T },
				{ "U", Input::Key::U },
				{ "V", Input::Key::V },
				{ "W", Input::Key::W },
				{ "X", Input::Key::X },
				{ "Y", Input::Key::Y },
				{ "Z", Input::Key::Z },

				{ "Zero", Input::Key::Zero },
				{ "One", Input::Key::One },
				{ "Two", Input::Key::Two },
				{ "Three", Input::Key::Three },
				{ "Four", Input::Key::Four },
				{ "Five", Input::Key::Five },
				{ "Six", Input::Key::Six },
				{ "Seven", Input::Key::Seven },
				{ "Eight", Input::Key::Eight },
				{ "Nine", Input::Key::Nine },

				{ "Left", Input::Key::Left },
				{ "Up", Input::Key::Up },
				{ "Right", Input::Key::Right },
				{ "Down", Input::Key::Down },

				{ "F1", Input::Key::F1 },
				{ "F2", Input::Key::F2 },
				{ "F3", Input::Key::F3 },
				{ "F4", Input::Key::F4 },
				{ "F5", Input::Key::F5 },
				{ "F6", Input::Key::F6 },
				{ "F7", Input::Key::F7 },
				{ "F8", Input::Key::F8 },
				{ "F9", Input::Key::F9 },
				{ "F10", Input::Key::F10 },
				{ "F11", Input::Key::F11 },
				{ "F12", Input::Key::F12 },
				{ "F13", Input::Key::F13 },
				{ "F14", Input::Key::F14 },
				{ "F15", Input::Key::F15 },
				{ "F16", Input::Key::F16 },
				{ "F17", Input::Key::F17 },
				{ "F18", Input::Key::F18 },
				{ "F19", Input::Key::F19 },
				{ "F20", Input::Key::F20 },
				{ "F21", Input::Key::F21 },
				{ "F22", Input::Key::F22 },
				{ "F23", Input::Key::F23 },
				{ "F24", Input::Key::F24 },

				{ "LeftAlt", Input::Key::LeftAlt },
				{ "LeftControl", Input::Key::LeftControl },
				{ "LeftShift", Input::Key::LeftShift },
				{ "LeftBracket", Input::Key::LeftBracket },
				{ "LeftGui", Input::Key::LeftGui },

				{ "RightAlt", Input::Key::RightAlt },
				{ "RightControl", Input::Key::RightControl },
				{ "RightShift", Input::Key::RightShift },
				{ "RightBracket", Input::Key::RightBracket },
				{ "RightGui", Input::Key::RightGui },

				{ "PageDown", Input::Key::PageDown },
				{ "PageUp", Input::Key::PageUp },

				{ "Keypad0", Input::Key::Keypad0 },
				{ "Keypad00", Input::Key::Keypad00 },
				{ "Keypad000", Input::Key::Keypad000 },
				{ "Keypad1", Input::Key::Keypad1 },
				{ "Keypad2", Input::Key::Keypad2 },
				{ "Keypad3", Input::Key::Keypad3 },
				{ "Keypad4", Input::Key::Keypad4 },
				{ "Keypad5", Input::Key::Keypad5 },
				{ "Keypad6", Input::Key::Keypad6 },
				{ "Keypad7", Input::Key::Keypad7 },
				{ "Keypad8", Input::Key::Keypad8 },
				{ "Keypad9", Input::Key::Keypad9 },
				{ "KeypadA", Input::Key::KeypadA },
				{ "KeypadB", Input::Key::KeypadB },
				{ "KeypadC", Input::Key::KeypadC },
				{ "KeypadD", Input::Key::KeypadD },
				{ "KeypadE", Input::Key::KeypadE },
				{ "KeypadF", Input::Key::KeypadF },
				{ "KeypadAmpersand", Input::Key::KeypadAmpersand },
				{ "KeypadAt", Input::Key::KeypadAt },
				{ "KeypadBackspace", Input::Key::KeypadBackspace },
				{ "KeypadBinary", Input::Key::KeypadBinary },
				{ "KeypadClear", Input::Key::KeypadClear },
				{ "KeypadClearEntry", Input::Key::KeypadClearEntry },
				{ "KeypadColon", Input::Key::KeypadColon },
				{ "KeypadComma", Input::Key::KeypadComma },
				{ "KeypadAmpersandAmpersand", Input::Key::KeypadAmpersandAmpersand },
				{ "KeypadBarBar", Input::Key::KeypadBarBar },
				{ "KeypadDecimal", Input::Key::KeypadDecimal },
				{ "KeypadForwardSlash", Input::Key::KeypadForwardSlash },
				{ "KeypadEnter", Input::Key::KeypadEnter },
				{ "KeypadEquals", Input::Key::KeypadEquals },
				{ "KeypadEqualsAS400", Input::Key::KeypadEqualsAS400 },
				{ "KeypadExclamation", Input::Key::KeypadExclamation },
				{ "KeypadGreater", Input::Key::KeypadGreater },
				{ "KeypadLess", Input::Key::KeypadLess },
				{ "KeypadPound", Input::Key::KeypadPound },
				{ "KeypadHexadecimal", Input::Key::KeypadHexadecimal },
				{ "KeypadLeftBrace", Input::Key::KeypadLeftBrace },
				{ "KeypadLeftParenthesis", Input::Key::KeypadLeftParenthesis },
				{ "KeypadMemAdd", Input::Key::KeypadMemAdd },
				{ "KeypadMemClear", Input::Key::KeypadMemClear },
				{ "KeypadMemDivide", Input::Key::KeypadMemDivide },
				{ "KeypadMemMultiply", Input::Key::KeypadMemMultiply },
				{ "KeypadMemRecall", Input::Key::KeypadMemRecall },
				{ "KeypadMemStore", Input::Key::KeypadMemStore },
				{ "KeypadMemSubtract", Input::Key::KeypadMemSubtract },
				{ "KeypadHyphen", Input::Key::KeypadHyphen },
				{ "KeypadAsterisk", Input::Key::KeypadAsterisk },
				{ "KeypadOctal", Input::Key::KeypadOctal },
				{ "KeypadPercent", Input::Key::KeypadPercent },
				{ "KeypadPeriod", Input::Key::KeypadPeriod },
				{ "KeypadPlus", Input::Key::KeypadPlus },
				{ "KeypadPlusMinus", Input::Key::KeypadPlusMinus },
				{ "KeypadPower", Input::Key::KeypadPower },
				{ "KeypadRightBrace", Input::Key::KeypadRightBrace },
				{ "KeypadRightParenthesis", Input::Key::KeypadRightParenthesis },
				{ "KeypadSpace", Input::Key::KeypadSpace },
				{ "KeypadTab", Input::Key::KeypadTab },
				{ "KeypadBar", Input::Key::KeypadBar },
				{ "KeypadXor", Input::Key::KeypadXor },

				{ "BrightnessUp", Input::Key::BrightnessUp },
				{ "BrightnessDown", Input::Key::BrightnessDown },

				{ "VolumeUp", Input::Key::VolumeUp },
				{ "VolumeDown", Input::Key::VolumeDown },

				{ "AudioMute", Input::Key::AudioMute },
				{ "AudioNext", Input::Key::AudioNext },
				{ "AudioPlay", Input::Key::AudioPlay },
				{ "AudioPrevious", Input::Key::AudioPrevious },
				{ "AudioStop", Input::Key::AudioStop },

				{ "AcBack", Input::Key::AcBack },
				{ "AcBookmarks", Input::Key::AcBookmarks },
				{ "AcForward", Input::Key::AcForward },
				{ "AcHome", Input::Key::AcHome },
				{ "AcRefresh", Input::Key::AcRefresh },
				{ "AcSearch", Input::Key::AcSearch },
				{ "AcStop", Input::Key::AcStop },

				{ "IlluminationDown", Input::Key::IlluminationDown },
				{ "IlluminationUp", Input::Key::IlluminationUp },
				{ "IlluminationToggle", Input::Key::IlluminationToggle },

				{ "Backslash", Input::Key::Backslash },
				{ "Backspace", Input::Key::Backspace },
				{ "Comma", Input::Key::Comma },
				{ "Quote", Input::Key::Quote },
				{ "Again", Input::Key::Again },
				{ "AltErase", Input::Key::AltErase },
				{ "Application", Input::Key::Application },
				{ "Calculator", Input::Key::Calculator },
				{ "Cancel", Input::Key::Cancel },
				{ "CapsLock", Input::Key::CapsLock },
				{ "Clear", Input::Key::Clear },
				{ "ClearAgain", Input::Key::ClearAgain },
				{ "Computer", Input::Key::Computer },
				{ "Copy", Input::Key::Copy },
				{ "CrSel", Input::Key::CrSel },
				{ "CurrencySubUnit", Input::Key::CurrencySubUnit },
				{ "CurrencyUnit", Input::Key::CurrencyUnit },
				{ "Cut", Input::Key::Cut },
				{ "DecimalSeparator", Input::Key::DecimalSeparator },
				{ "Del", Input::Key::Del },
				{ "DisplaySwitch", Input::Key::DisplaySwitch },
				{ "Eject", Input::Key::Eject },
				{ "End", Input::Key::End },
				{ "Equals", Input::Key::Equals },
				{ "Escape", Input::Key::Escape },
				{ "Execute", Input::Key::Execute },
				{ "ExSel", Input::Key::ExSel },
				{ "Find", Input::Key::Find },
				{ "Grave", Input::Key::Grave },
				{ "Help", Input::Key::Help },
				{ "Home", Input::Key::Home },
				{ "Insert", Input::Key::Insert },
				{ "Mail", Input::Key::Mail },
				{ "MediaSelect", Input::Key::MediaSelect },
				{ "Menu", Input::Key::Menu },
				{ "Hyphen", Input::Key::Hyphen },
				{ "ModeSwitch", Input::Key::ModeSwitch },
				{ "Mute", Input::Key::Mute },
				{ "Numlock", Input::Key::Numlock },
				{ "Oper", Input::Key::Oper },
				{ "Out", Input::Key::Out },
				{ "Paste", Input::Key::Paste },
				{ "Pause", Input::Key::Pause },
				{ "Period", Input::Key::Period },
				{ "Power", Input::Key::Power },
				{ "PrintScreen", Input::Key::PrintScreen },
				{ "Prior", Input::Key::Prior },
				{ "Enter", Input::Key::Enter },
				{ "ScrollLock", Input::Key::ScrollLock },
				{ "Select", Input::Key::Select },
				{ "Semicolon", Input::Key::Semicolon },
				{ "Separator", Input::Key::Separator },
				{ "ForwardSlash", Input::Key::ForwardSlash },
				{ "Sleep", Input::Key::Sleep },
				{ "Space", Input::Key::Space },
				{ "Stop", Input::Key::Stop },
				{ "SysReq", Input::Key::SysReq },
				{ "Tab", Input::Key::Tab },
				{ "ThousandsSeparator", Input::Key::ThousandsSeparator },
				{ "Undo", Input::Key::Undo },
				{ "WorldWideWeb", Input::Key::WorldWideWeb }
            });
    }

    auto Type<Input::Key>::ToV8(v8::Isolate& isolate, const Input::Key& value) -> v8::Local<V8T>
    {
        return EnumType<Input::Key>::ToV8(isolate, value);
    }

    std::optional<Input::Key> Type<Input::Key>::FromV8(v8::Isolate& isolate, const v8::Local<v8::Value>& value)
    {
        return EnumType<Input::Key>::FromV8(isolate, value);
    }
}